apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: .github
  description: Backstage catalog entry
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: sin-asignar